version: "3"

services: 
  backend:
    container_name: backend
    build: backend/
    env_file:
      - ".env"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports: 
      - 3001:3001
    depends_on:
      - db
      - adminer
    volumes:
      - ./backend/src:/app/src

  db: 
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080