version: "3"

services: 
  backend:
    container_name: backend
    build: backend/
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports: 
      - 4000:7654
    volumes:
      - ./backend/src:/app/src

  frotend:
    container_name: frontend
    build: frontend/
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src

